### ISSUE TITLE
Adapt the dashboard to all the different tasking manager

### ISSUE THREAD

**Issue by LorenzoStucchi** [CartONG/mapathon_dashboard#15] opened 2019-09-25 14:54 UTC
I tried to do it in a [issues](https://github.com/LorenzoStucchi/mapathon_dashboard/issues/2) in a [branch](https://github.com/LorenzoStucchi/mapathon_dashboard/tree/multiple-test) of my fork. But I'm not able to understand why there is this final error.

**Comment by regazzoj** [comment] 2020-04-17 13:32
Hi,
Sorry for the (very) late answer.
I would like to help you, but I don't know your error you were talking about.
Can you tell me more ?

I tried your project and it works, except for the tiles (see the last merge pull request) but it is fixed now, and I had to add an exception for the "https://tasks-teachosm.hotosm.org/" website.
It looks like the certificate is not a valid one.

Edit : you should query "https://tasks.teachosm.org/" address instead of the one you are query to avoid CORS problem.
Tell me if you want me to modify you code project.
And now that I understand what this issue is, I will work on it soon.

**Comment by LorenzoStucchi** [comment] 2020-04-18 09:38
Hi,
My idea was to make it possible to use the dashboard to all the tasking manager. So the user inserts the link to the task and the dashboard is used to all the different tasking manager.

For the URL, I had to change it because this "https://tasks.teachosm.org/" was no more reachable for some days.

**Comment by regazzoj** [comment] 2020-04-18 09:47
Hello Lorenzo,

Yeah, I got it now ! I get all the different tasking manager that I found and with SSL enabled (https).
Here is my list :
World wide
https://tasks.teachosm.org/
https://osm.earth/
https://tasks.hotosm.org/

American
https://tasks.atlasurbano.org/login?redirect_to=%2F
https://tareas.openstreetmap.co/
https://osmcolorado.com/
https://tasks.openstreetmap.us/

Europe
https://tasks.osm.ch/
https://osmit-tm3.wmflabs.org/login?redirect_to=%2F
https://tasks.osm-hr.org/
https://tarefas.openstreetmap.pt/
https://tareas.openstreetmap.es/

But I think it will be easier to have a menu options and choose the tasking manager that we want instead of asking the user to write it down, don't you ?

By the way, you wrote about "a final error" in your first post, can you tell me more about it ?

**Comment by LorenzoStucchi** [comment] 2020-04-18 10:17
I think that is more simple to insert a link like "https://tasks.teachosm.org/project/977" because the URL of the different tasking manager could change (like for the one of the Italian community) and this list should be continuously updated. 

For the error I don't remember what it was, I will try to retry it.

**Comment by regazzoj** [comment] 2020-04-20 13:26
I find your solution less user-friendly and more subject to errors in URL, this is why I suggested to have a menu options.
Moreover, with a menu options, we can change the tasking manager image in the header, so the page would be more consistent I think.
I'll give it a try soon, and let you know when I'm done so maybe you could give me a feedback, and we will improve/change it, if needed.

PS: I lock this issue for now, because it is a duplicate of #3

**Closed as completed** 2020-05-08 12:13 UTC
Labels: duplicate, WIP
